### ISSUE TITLE
static_qt_plugins.cpp causes warnings on Visual Studio 2013

### ISSUE THREAD

**Issue by Knitschi** [hunter-packages/QtCMakeExtra#1]
I have integrated the Qt hunter package into my codebase and now I am running into problems. The libraries that use Qt now contain the static_qt_plugins.cpp file which does not compile without warnings.
This is a problem for me as I have the "warning treated as error" option on.

Is there a workaround for this?

**Comment by ruslo** [comment]
> which does not compile without warnings

What kind of warning is it?

> now contain the static_qt_plugins.cpp file

This file contains only a few lines of Qt's macro, so I guess problem is in Qt's code in fact.

> Is there a workaround for this?

I think you can disable warning just for one file by modifying `COMPILE_FLAGS` property of a source:
- https://cmake.org/cmake/help/latest/manual/cmake-properties.7.html#properties-on-source-files

**Comment by Knitschi** [comment]
Yes, I forgot to mention that those are warnings from the QtPlugin header. In the rest of my code I have all Qt header files in one precompiled header file were I can conveniently put #pragmas around the includes to switch off warnings from external code. This does not work for the static_qt_plugins.cpp file as it is not under my control and added directly as a source for the targets that use qt.

I will try to change the files warning level with the source file properties.

IS the static_qt_plugins.cpp file also included if I use dynamic qt libraries?

I know tried to change the compile flags of the file but It can not be found with

```
get_source_file_property(VAR static_qt_plugins.cpp LOCATION)
message( ${VAR} )
```

this only prints NOTFOUND while it works for the files that I add to the target.
How is the file added anyways? Is it not a source file?

**Comment by ruslo** [comment]
> IS the static_qt_plugins.cpp file also included if I use dynamic qt libraries?

Nope

> How is the file added anyways?

Using [INTERFACE_SOURCES](https://cmake.org/cmake/help/latest/prop_tgt/INTERFACE_SOURCES.html) feature. You can "grep" the source file you're interested in and check by what target it was added, e.g. `static_qt_QJp2Plugin.cpp` added by `Qt5::QJp2Plugin`:
- https://github.com/hunter-packages/QtCMakeExtra/blob/b567f44907b7ace824f5b8077feeb9bf30d61bef/cmake/Qt5Gui_ZZZ_HunterPlugin.cmake#L128

Also I think this project may interest you:
- https://github.com/ruslo/leathers

**Comment by Knitschi** [comment]
Thanks for the tip with the leathers project. I will take a look at it when I start making a linux build work. For now I "fixed" the problem by using dynamic linkage.

**Comment by ruslo** [comment]
@Knitschi feel free to close if this one is resolved

**Comment by Knitschi** [comment]
Ok to close this I repeat the solution. I set the source file properties for the interface source files with the following cmake code:

```
macro( remove_warning_flags_for_some_external_files targetName )

     # blacklist of trouble makers
    set( externalFiles 
        static_qt_plugins.cpp
    )

    get_target_property( linkedLibraries ${targetName} LINK_LIBRARIES )

    foreach(library ${linkedLibraries})
        if( TARGET ${library}) # prevent errors with get_property call on our own targets.
            get_target_property( isImported ${library} IMPORTED)
            if( ${isImported})      # prevent errors with get_property call on our own targets.
                get_property( sources TARGET ${library} PROPERTY INTERFACE_SOURCES )
                foreach(source ${sources})

                    get_filename_component(shortName ${source} NAME)
                    if( ${shortName} IN_LIST externalFiles)

                        get_source_file_property( flags ${shortName} COMPILE_FLAGS)
                        if( ${flags} STREQUAL NOTFOUND)
                            set(flags "")
                        endif()
                        set_source_files_properties(${source} PROPERTIES COMPILE_FLAGS "-w ${flags}")
                    endif()
                endforeach()
            endif()
        endif()
    endforeach()
endmacro()
```
